spring:
  application:
    name: stock-manager

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5332/stockdb}
    username: ${SPRING_DATASOURCE_USERNAME:stockuser}
    password: ${SPRING_DATASOURCE_PASSWORD:stockpass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

  task:
    scheduling:
      pool:
        size: 2

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

# Security Configuration
security:
  jwt:
    secret-key: ${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiration-time: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
  show-actuator: false
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match: /api/**
  packages-to-scan: dev.amirgol.stockmanager.controller

logging:
  level:
    dev.amirgol.stockmanager: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
